name:  Continuous Deployment

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: windows-latest
    env:
      PackageOutputPath: '${{ github.workspace }}\package'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     source-url: https://nuget.pkg.github.com/<organization>/index.json

    - name: Build
      run: | 
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True src
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True tests

    - name: Test
      run: | 
        dotnet test tests

    - name: Publish
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        dotnet nuget push '${{ env.PackageOutputPath }}\*' --source github --skip-duplicate
